// Code generated by bitproto. DO NOT EDIT.

#ifndef __BITPROTO__FIELD_BALL_H__
#define __BITPROTO__FIELD_BALL_H__ 1

#include <inttypes.h>
#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

#include "bitproto.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include "Vector_bp.h"
#include "Time_bp.h"

// Number of bytes to encode struct BallState
#define BYTES_LENGTH_BALL_STATE 7

struct BallState {
    struct Vector2 position; // 28bit
    struct Vector2 velocity; // 28bit
};

// Number of bytes to encode struct BallModel
#define BYTES_LENGTH_BALL_MODEL 28

struct BallModel {
    struct Vector2 last_perception; // 28bit
    struct BallState estimate; // 56bit
    Timestamp time_when_last_seen; // 64bit
    Timestamp time_when_disappeared; // 64bit
    uint8_t seen_percentage; // 7bit
};

// Encode struct BallState to given buffer s.
int EncodeBallState(struct BallState *m, unsigned char *s);
// Decode struct BallState from given buffer s.
int DecodeBallState(struct BallState *m, unsigned char *s);
// Format struct BallState to a json format string.
int JsonBallState(struct BallState *m, char *s);

// Encode struct BallModel to given buffer s.
int EncodeBallModel(struct BallModel *m, unsigned char *s);
// Decode struct BallModel from given buffer s.
int DecodeBallModel(struct BallModel *m, unsigned char *s);
// Format struct BallModel to a json format string.
int JsonBallModel(struct BallModel *m, char *s);

void BpXXXProcessBallState(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatBallState(void *data, struct BpJsonFormatContext *ctx);

void BpXXXProcessBallModel(void *data, struct BpProcessorContext *ctx);
void BpXXXJsonFormatBallModel(void *data, struct BpJsonFormatContext *ctx);

#if defined(__cplusplus)
}
#endif

#endif