// Code generated by bitproto. DO NOT EDIT.

#include "bitproto.h"
#include "FieldBall_bp.h"

void BpFieldDescriptorsInitBallState(struct BallState *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->position), BpMessage(28, sizeof(struct Vector2), BpXXXProcessVector2, BpXXXJsonFormatVector2), "position");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->velocity), BpMessage(28, sizeof(struct Vector2), BpXXXProcessVector2, BpXXXJsonFormatVector2), "velocity");
}

void BpXXXProcessBallState(void *data, struct BpProcessorContext *ctx) {
    struct BallState *m = (struct BallState *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitBallState(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 56, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatBallState(void *data, struct BpJsonFormatContext *ctx) {
    struct BallState *m = (struct BallState *)(data);
    struct BpMessageFieldDescriptor field_descriptors[2];
    BpFieldDescriptorsInitBallState(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 2, 56, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeBallState(struct BallState *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessBallState((void *)m, &ctx);
    return 0;
}

int DecodeBallState(struct BallState *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessBallState((void *)m, &ctx);
    return 0;
}

int JsonBallState(struct BallState *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatBallState((void *)m, &ctx);
    return ctx.n;
}

void BpFieldDescriptorsInitBallModel(struct BallModel *m, struct BpMessageFieldDescriptor *fds) {
    fds[0] = BpMessageFieldDescriptor((void *)&(m->last_perception), BpMessage(28, sizeof(struct Vector2), BpXXXProcessVector2, BpXXXJsonFormatVector2), "last_perception");
    fds[1] = BpMessageFieldDescriptor((void *)&(m->estimate), BpMessage(56, sizeof(struct BallState), BpXXXProcessBallState, BpXXXJsonFormatBallState), "estimate");
    fds[2] = BpMessageFieldDescriptor((void *)&(m->time_when_last_seen), BpAlias(64, sizeof(Timestamp), BpXXXProcessTimestamp, BpXXXJsonFormatTimestamp, BP_TYPE_INT), "time_when_last_seen");
    fds[3] = BpMessageFieldDescriptor((void *)&(m->time_when_disappeared), BpAlias(64, sizeof(Timestamp), BpXXXProcessTimestamp, BpXXXJsonFormatTimestamp, BP_TYPE_INT), "time_when_disappeared");
    fds[4] = BpMessageFieldDescriptor((void *)&(m->seen_percentage), BpUint(7, sizeof(uint8_t)), "seen_percentage");
}

void BpXXXProcessBallModel(void *data, struct BpProcessorContext *ctx) {
    struct BallModel *m = (struct BallModel *)(data);
    struct BpMessageFieldDescriptor field_descriptors[5];
    BpFieldDescriptorsInitBallModel(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 5, 219, field_descriptors);
    BpEndecodeMessage(&descriptor, ctx, data);
}

void BpXXXJsonFormatBallModel(void *data, struct BpJsonFormatContext *ctx) {
    struct BallModel *m = (struct BallModel *)(data);
    struct BpMessageFieldDescriptor field_descriptors[5];
    BpFieldDescriptorsInitBallModel(m, field_descriptors);
    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, 5, 219, field_descriptors);
    BpJsonFormatMessage(&descriptor, ctx, data);
}

int EncodeBallModel(struct BallModel *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(true, s);
    BpXXXProcessBallModel((void *)m, &ctx);
    return 0;
}

int DecodeBallModel(struct BallModel *m, unsigned char *s) {
    struct BpProcessorContext ctx = BpProcessorContext(false, s);
    BpXXXProcessBallModel((void *)m, &ctx);
    return 0;
}

int JsonBallModel(struct BallModel *m, char *s) {
    struct BpJsonFormatContext ctx = BpJsonFormatContext(s);
    BpXXXJsonFormatBallModel((void *)m, &ctx);
    return ctx.n;
}