// Code generated by bitproto. DO NOT EDIT.

#include "bitproto.h"
#include "Time_bp.h"

void BpXXXProcessTimestamp(void *data, struct BpProcessorContext *ctx) {
    struct BpAliasDescriptor descriptor = BpAliasDescriptor(BpInt(64, sizeof(int64_t)));
    BpEndecodeAlias(&descriptor, ctx, data);
}

void BpXXXJsonFormatTimestamp(void *data, struct BpJsonFormatContext *ctx) {
    struct BpAliasDescriptor descriptor = BpAliasDescriptor(BpInt(64, sizeof(int64_t)));
    BpJsonFormatAlias(&descriptor, ctx, data);
}